LibraryCarpentry/lc-sql

- README.md
- _episodes/01-introduction.md
#8 
Changes import and db create to reflect use of new database gui (db4s rather than firefox).
> change database create and import instructions to reflect use of DB4S

- _episodes/01-introduction.md
This addresses 'update the dataset description #30' -  https://github.com/data-lessons/library-sql-DEPRECATED/issues/30
> Update Dataset Description

- _episodes/03-aggregation.md
> Update lesson03 to DBBrowser

- _episodes/04-joins-aliases.md
Addresses #2 
Also added a small clarification that additional tables need to be imported before doing this lesson.
> Update lesson 04 to DB Browser

- index.md
- setup.md
Removed the sqlite prereq on the main page and added an installation note for windows on the setup page.
Addresses #13
> Dbbrowser setup instructions

- _episodes/01-introduction.md
- We made the objectives more reflective of the content within the episode
- We updated the essential questions
- We updated the key points
> Update 01-introduction Overview

- setup.md
> typo and clarification on setup page

- _episodes/01-introduction.md
Same as https://github.com/LibraryCarpentry/lc-shell/pull/9 ;-)
> Hyperlink DOI against preferred resolver

- _episodes/05-supplement.md
SQL is a query language. Hopefully this change still captures the original intent.
> clarify objectives and key points

- setup.md
Hello, I just came across a few (4) typos in this setup page.  I have corrected them.
Best,
David.
> Fixed a number of typos on the setup file

- _episodes/04-joins-aliases.md
Database values for no language is an empty string instead of NULL in the Language table.
> Fixed WHERE clause in Challenge 3 solution

- _episodes/04-saving-queries.md
Originally part of aggregating queries episode but per @JordanPedersen moved to new episode.
> Create saving queries episode

- _episodes/07-database-design.md
Reverts LibraryCarpentry/lc-sql#54 based on https://github.com/LibraryCarpentry/lc-sql/issues/43#issuecomment-496648993 feedback
> Revert "Expand normalisation section, add tables, normal forms"

- _episodes/07-database-design.md
Broke up the text and expanded some of the explanations. Removed mentioning the one-to-one relationship model as I don't see it too often in real implementations. Address #59
> Break up ER diagram text and add clarifications

- _episodes/02-basic-queries.md
line 155: changed clasuse --> clause
line 155: changed book end --> book-end
line 185: changes lets --> let's
Please delete the text below before submitting your contribution.
> Fixed 3 typos in 02-basic-queries.md

- _episodes/02-selecting-sorting-data.md
Based on https://github.com/LibraryCarpentry/lc-sql/issues/52, create an episode that draws from 'What is a query?', 'Unique values', and 'Sorting' in 'Basic queries' episode.
- Revise questions, objectives, and keypoints
- Add more explanation of what is a query
- Update writing my first query to include information about opening DB Browser, database, table
- Add further explanation to unique values
- Update SQL statements to title case for fields
- Add further Markdown `` for keywords and fields
- Add note about the semicolon use
> Create selecting and sorting data episode

- _episodes/03-filtering.md
Create filtering episode based on https://github.com/LibraryCarpentry/lc-sql/issues/52
> Create filtering episode

- _episodes/07-saving-queries.md
- Update CREATE VIEW challenge to articles-journals join
- Update issns to ISSNs to align with other queries
> Update create view query challenge language

- _episodes/01-introduction.md
Made a few small corrections.  Removed table at end of page, as individuals will find more comprehensive documentation on the platforms' website, and because the focus of this lesson is not using multiple platforms.  Replaced with a table explaining data types more generally and how they are represented in the platform used in this lesson.
> Table of Data Types + small corrections

- _episodes/08-database-design.md
> Update intro to sql link

- setup.md
- change "->" to ">"
- add single quotes to menu items
> Update navigation style

- _episodes/06-joins-aliases.md
Responds to https://github.com/LibraryCarpentry/lc-sql/issues/97
Thanks @jfrisina for finding this resource!
> Add SQL Join Types Explained Visually

- _episodes/06-joins-aliases.md
Reverts LibraryCarpentry/lc-sql#108 I merged this, but I should have waited (I did not see the comment before I merged). @libcce @librarianlise I am reverting and making a new PR. Sorry about that.
> Revert "Add SQL Join Types Explained Visually"

- _extras/guide.md
See Import CSV in SQLite section
Responds to https://github.com/LibraryCarpentry/lc-sql/issues/105
> Add DOAJ SQLite example

- _episodes/01-introduction.md
1. Very minor grammatical change (adding a comma to correct a run-on sentence).
2. Added a contextual phrase to align the use of the pronoun "we" with "librarians"
> Copyedits - Very minor

- _episodes/04-aggregating-calculating.md
AVG(Citation_Count) needs to match AVG(Citation_Count) to be executed without an error.
> Avg_Citation_Count needs to be rewritten

- _episodes/06-joins-aliases.md
Updated join diagram with a better size.
> Changed to resized join diagram

- _episodes/01-introduction.md
- _episodes/06-joins-aliases.md
Changed some language in the Intro to make it more friendly to non-librarian library workers. Adjusted a bit of awkward language
> Kristindawn changelibworkerlanguage

- _episodes/08-database-design.md
> Expanded terminology, edited wording 

- _episodes/09-create.md
- _episodes/create.md
Dear all,
here is a first draft for a section about creating tables and modifying data.
I am looking forward for your suggestions and comments.
Greetings,
Julika
> New section 9: Creating tables and modifying data

- _episodes/09-create.md
> Correct link

- _episodes/06-joins-aliases.md
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.
----
Line 35 ![Join Diagram for Example](../assets/img/left-join-articles-journals_40.png) left-join-articles-journals_40.png is to visualize the join example in lines 24-27,
which however is a (inner) join; I propose to change the PNG accordingly.
Line 121, There are different types of joins which you can learn more about at [SQL Joins Explained](http://www.sql-join.com/sql-join-types).
the web-link http://www.sql-join.com/sql-join-types resolves to https://www.talend.com/
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If …
> Lesson Contribution - Join types; JN

- _includes/check_transition_variables.html
- _includes/lesson_footer.html
- _includes/life_cycle.html
- _includes/navbar.html
- _layouts/base.html
- assets/css/lesson.scss
- bin/boilerplate/_config.yml
Bringing the lesson template up-to-date in preparation for the planned infrastructure transition.
This built successfully on my system, and I am 99% sure it will do so on GitHub too when merged.
> Update to final version of styles lesson template

- learners/setup.md
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Fixes #145
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
We had to create a new record in Zenodo to add a cleaned-up version of the example dataset, with the __MACOSX folder removed. This PR updates the Setup instructions to point to that new Zenodo record.
_If any relevant discussions have taken place elsewhere, please provide links to these._
n/a
> Update DOI for example dataset
